### ISSUE TITLE
weird verbs in there

### ISSUE THREAD

**Issue by Lakedaemon** [unimorph/fra#1]
Hello

I'm french and I just had a look at the french unimorph file.
There are some really weird entries in there.
For exemple

Enseigner (to teach) is a french verb but it is missing though 
Ensaigner is in the file but doesn't exist in the french language (disclaimer : I have never heard/nor used that verb in the last 43 years)

Some other entries like 
purporter (what is that ?) shouldn't be in there...

How did you build this file ?

**Comment by Lakedaemon** [comment]
Actually, a lot of verbs in there don't make any sense like : 
aanchrer, abader, abaïer, abaissier, abaler, abaliéner, abaloger, ...

I take it that the fra file is about french written/spoken in france in the 21/20th century, right ?

**Comment by Lakedaemon** [comment]
mmmh, maybee I was mistaken (I hadn't understood the puprose of this file).
This input might be used (with fictitious verbs) to train a neural model that manages to inflectnormal non-fictitious verbs the right way...with state of the art results (If what I found on the internet is the right documentation for this)

**Comment by aryamccarthy** [comment]
Hi Olivier, thanks for letting us know! And sorry that we're just now looking at this. If you catch mistakes in UniMorph, please submit a PR! Our data for French is scraped from Wiktionary. Some verbs may not be in common use, and sometimes Wiktionary needs to be corrected.

**Comment by mcdowlinguist** [comment]
Hi, our team is wrestling with this too. Just by poking around and comparing the file with Wiktionary entries, it appears there's a good number of Old French (ancien français) forms that aren't filtered out.

**Comment by kbatsuren** [comment]
I assume that the `Old French` issue is fixed with the new update but it is named with `fra.um4`
